### ISSUE TITLE
Implement better exception handling in ServoParty

### ISSUE THREAD

**Issue by Conr86** [SFXRescue/SARTRobot#7]
At the moment, check out what happens when something goes catastrophically wrong.

```python
Error in connection handler
Traceback (most recent call last):
  File "/home/sart/SARTRobot/servo_party.py", line 68, in move_raw
    self.sc.set_speed(Servo.LEFT_FRONT, left)
  File "/usr/local/lib/python3.6/dist-packages/pyax12/connection.py", line 1482, in set_speed
    self.write_data(dynamixel_id, pk.MOVING_SPEED, params)
  File "/usr/local/lib/python3.6/dist-packages/pyax12/connection.py", line 216, in write_data
    self.send(inst_packet)
  File "/usr/local/lib/python3.6/dist-packages/pyax12/connection.py", line 102, in send
    self.flush()      # TODO: make a (synchronous) flush_in() and flush_out() instead
  File "/usr/local/lib/python3.6/dist-packages/pyax12/connection.py", line 161, in flush
    self.serial_connection.flushInput()
  File "/usr/local/lib/python3.6/dist-packages/serial/serialutil.py", line 584, in flushInput
    self.reset_input_buffer()
  File "/usr/local/lib/python3.6/dist-packages/serial/serialposix.py", line 595, in reset_input_buffer
    termios.tcflush(self.fd, termios.TCIFLUSH)
termios.error: (5, 'Input/output error')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/websockets/server.py", line 152, in handler
    yield from self.ws_handler(self, path)
  File "/home/sart/SARTRobot/control_receiver.py", line 179, in main
    self.message_handler(buf)
  File "/home/sart/SARTRobot/control_receiver.py", line 137, in message_handler
    self.keyboard_handler(control, value)
  File "/home/sart/SARTRobot/control_receiver.py", line 71, in keyboard_handler
    self.servo_party.move(speed, speed)
  File "/home/sart/SARTRobot/servo_party.py", line 123, in move
    self.move_raw(left, right)
  File "/home/sart/SARTRobot/servo_party.py", line 74, in move_raw
    self.crash(left, right)
  File "/home/sart/SARTRobot/servo_party.py", line 93, in crash
    self.close()
  File "/home/sart/SARTRobot/servo_party.py", line 56, in close
    self.stop();
  File "/home/sart/SARTRobot/servo_party.py", line 47, in stop
    self.sc.set_speed(1, 0)
  File "/usr/local/lib/python3.6/dist-packages/pyax12/connection.py", line 1482, in set_speed
    self.write_data(dynamixel_id, pk.MOVING_SPEED, params)
  File "/usr/local/lib/python3.6/dist-packages/pyax12/connection.py", line 216, in write_data
    self.send(inst_packet)
  File "/usr/local/lib/python3.6/dist-packages/pyax12/connection.py", line 102, in send
    self.flush()      # TODO: make a (synchronous) flush_in() and flush_out() instead
  File "/usr/local/lib/python3.6/dist-packages/pyax12/connection.py", line 161, in flush
    self.serial_connection.flushInput()
  File "/usr/local/lib/python3.6/dist-packages/serial/serialutil.py", line 584, in flushInput
    self.reset_input_buffer()
  File "/usr/local/lib/python3.6/dist-packages/serial/serialposix.py", line 595, in reset_input_buffer
    termios.tcflush(self.fd, termios.TCIFLUSH)
termios.error: (5, 'Input/output error')
```

I have a crash handler function which tries to stop the servos and close the connection, but that just throws another exception. So, what do we do?

Possibly, in the crash handler, rather than attempt to stop the servos and close the connection, we try to reopen it, and then stop the servos.

Just an idea.

**Comment by Conr86** [comment]
It hasn't been tested but 512cc289cc094714c2c2cd90e22e6d20ad19a34c should fix this issue
